// Word database for the daily vocab game
// Each entry: { word, definition, type, origin, difficulty }
const WORDS = [
  { word: "ephemeral", definition: "Lasting for a very short time; transient.", type: "adjective", origin: "Greek" },
  { word: "cacophony", definition: "A harsh, discordant mixture of sounds.", type: "noun", origin: "Greek" },
  { word: "serendipity", definition: "The occurrence of events by chance in a happy or beneficial way.", type: "noun", origin: "English" },
  { word: "eloquent", definition: "Fluent or persuasive in speaking or writing.", type: "adjective", origin: "Latin" },
  { word: "ubiquitous", definition: "Present, appearing, or found everywhere.", type: "adjective", origin: "Latin" },
  { word: "pernicious", definition: "Having a harmful effect, especially in a gradual or subtle way.", type: "adjective", origin: "Latin" },
  { word: "surreptitious", definition: "Kept secret, especially because it would not be approved of.", type: "adjective", origin: "Latin" },
  { word: "melancholy", definition: "A deep, persistent sadness or gloom.", type: "noun", origin: "Greek" },
  { word: "resilient", definition: "Able to recover quickly from difficult conditions.", type: "adjective", origin: "Latin" },
  { word: "enigma", definition: "A person or thing that is mysterious, puzzling, or difficult to understand.", type: "noun", origin: "Greek" },
  { word: "voracious", definition: "Wanting or devouring great quantities of food or knowledge.", type: "adjective", origin: "Latin" },
  { word: "luminous", definition: "Full of or shedding light; bright or shining.", type: "adjective", origin: "Latin" },
  { word: "benevolent", definition: "Well-meaning and kindly; generous.", type: "adjective", origin: "Latin" },
  { word: "quintessence", definition: "The most perfect or typical example of a quality or class.", type: "noun", origin: "Latin" },
  { word: "wanderlust", definition: "A strong desire to travel and explore the world.", type: "noun", origin: "German" },
  { word: "aesthetic", definition: "Concerned with beauty or the appreciation of beauty.", type: "adjective", origin: "Greek" },
  { word: "clandestine", definition: "Kept secret or done secretively, especially because illicit.", type: "adjective", origin: "Latin" },
  { word: "magnanimous", definition: "Very generous or forgiving, especially toward a rival or less powerful person.", type: "adjective", origin: "Latin" },
  { word: "paradigm", definition: "A typical example or pattern of something; a model.", type: "noun", origin: "Greek" },
  { word: "labyrinth", definition: "A complicated irregular network of passages or paths; a maze.", type: "noun", origin: "Greek" },
  { word: "nostalgia", definition: "A sentimental longing for the past, typically for a happy period.", type: "noun", origin: "Greek" },
  { word: "audacious", definition: "Showing a willingness to take surprisingly bold risks.", type: "adjective", origin: "Latin" },
  { word: "zenith", definition: "The highest point reached by a celestial or other object; the peak.", type: "noun", origin: "Arabic" },
  { word: "pristine", definition: "In its original condition; unspoiled.", type: "adjective", origin: "Latin" },
  { word: "euphoria", definition: "A feeling or state of intense excitement and happiness.", type: "noun", origin: "Greek" },
  { word: "lethargic", definition: "Affected by lethargy; sluggish and apathetic.", type: "adjective", origin: "Greek" },
  { word: "catharsis", definition: "The process of releasing strong or repressed emotions.", type: "noun", origin: "Greek" },
  { word: "alchemy", definition: "A seemingly magical process of transformation or creation.", type: "noun", origin: "Arabic" },
  { word: "gregarious", definition: "Fond of company; sociable.", type: "adjective", origin: "Latin" },
  { word: "juxtapose", definition: "To place close together for contrasting effect.", type: "verb", origin: "Latin" },
  { word: "meticulous", definition: "Showing great attention to detail; very careful and precise.", type: "adjective", origin: "Latin" },
  { word: "nefarious", definition: "Wicked or criminal in nature.", type: "adjective", origin: "Latin" },
  { word: "opulent", definition: "Ostentatiously rich and luxurious.", type: "adjective", origin: "Latin" },
  { word: "placate", definition: "To make someone less angry or hostile.", type: "verb", origin: "Latin" },
  { word: "quagmire", definition: "A soft boggy area of land; a complex or difficult situation.", type: "noun", origin: "English" },
  { word: "recalcitrant", definition: "Having an obstinately uncooperative attitude.", type: "adjective", origin: "Latin" },
  { word: "sagacious", definition: "Having or showing keen mental discernment and good judgment.", type: "adjective", origin: "Latin" },
  { word: "tenacious", definition: "Tending to keep a firm hold of something; persistent.", type: "adjective", origin: "Latin" },
  { word: "umbrage", definition: "Offense or annoyance.", type: "noun", origin: "Latin" },
  { word: "verbose", definition: "Using or expressed in more words than are needed.", type: "adjective", origin: "Latin" },
  { word: "whimsical", definition: "Playfully quaint or fanciful, especially in an appealing way.", type: "adjective", origin: "English" },
  { word: "rapport", definition: "A close and harmonious relationship in which people understand each other.", type: "noun", origin: "French" },
  { word: "solitude", definition: "The state or situation of being alone.", type: "noun", origin: "Latin" },
  { word: "tangible", definition: "Perceptible by touch; clear and definite.", type: "adjective", origin: "Latin" },
  { word: "vivacious", definition: "Attractively lively and animated.", type: "adjective", origin: "Latin" },
  { word: "abscond", definition: "To leave hurriedly and secretly, typically to escape.", type: "verb", origin: "Latin" },
  { word: "debacle", definition: "A sudden and complete disaster or failure.", type: "noun", origin: "French" },
  { word: "exquisite", definition: "Extremely beautiful and delicate.", type: "adjective", origin: "Latin" },
  { word: "harbinger", definition: "A person or thing that announces or signals the approach of another.", type: "noun", origin: "French" },
  { word: "incandescent", definition: "Emitting light as a result of being heated; passionate.", type: "adjective", origin: "Latin" },
  { word: "kaleidoscope", definition: "A constantly changing pattern or sequence of objects or elements.", type: "noun", origin: "Greek" },
  { word: "mundane", definition: "Lacking interest or excitement; dull.", type: "adjective", origin: "Latin" },
  { word: "oblivion", definition: "The state of being unaware or unconscious of what is happening.", type: "noun", origin: "Latin" },
  { word: "panorama", definition: "An unbroken view of the whole region surrounding an observer.", type: "noun", origin: "Greek" },
  { word: "querulous", definition: "Complaining in a petulant or whining manner.", type: "adjective", origin: "Latin" },
  { word: "reverie", definition: "A state of being pleasantly lost in one's thoughts; a daydream.", type: "noun", origin: "French" },
  { word: "sycophant", definition: "A person who praises powerful people to gain advantage.", type: "noun", origin: "Greek" },
  { word: "trepidation", definition: "A feeling of fear or agitation about something that may happen.", type: "noun", origin: "Latin" },
  { word: "venerable", definition: "Accorded a great deal of respect due to age, wisdom, or character.", type: "adjective", origin: "Latin" },
  { word: "aberration", definition: "A departure from what is normal or expected.", type: "noun", origin: "Latin" },
  { word: "brevity", definition: "Concise and exact use of words in writing or speech.", type: "noun", origin: "Latin" },
  { word: "conundrum", definition: "A confusing and difficult problem or question.", type: "noun", origin: "English" },
  { word: "diaphanous", definition: "Light, delicate, and translucent.", type: "adjective", origin: "Greek" },
  { word: "effervescent", definition: "Vivacious and enthusiastic; giving off bubbles.", type: "adjective", origin: "Latin" },
  { word: "fastidious", definition: "Very attentive to and concerned about accuracy and detail.", type: "adjective", origin: "Latin" },
  { word: "gossamer", definition: "Something very light, thin, and insubstantial.", type: "noun", origin: "English" },
  { word: "halcyon", definition: "Denoting a period of time in the past that was idyllically happy and peaceful.", type: "adjective", origin: "Greek" },
  { word: "impetuous", definition: "Acting or done quickly and without thought or care.", type: "adjective", origin: "Latin" },
  { word: "jubilant", definition: "Feeling or expressing great happiness and triumph.", type: "adjective", origin: "Latin" },
  { word: "languish", definition: "To lose or lack vitality; to grow weak or feeble.", type: "verb", origin: "Latin" },
  { word: "nebulous", definition: "In the form of a cloud or haze; vague or ill-defined.", type: "adjective", origin: "Latin" },
  { word: "palatable", definition: "Pleasant to taste; acceptable or satisfactory.", type: "adjective", origin: "Latin" },
  { word: "resplendent", definition: "Impressive and attractive in appearance; dazzling.", type: "adjective", origin: "Latin" },
  { word: "sardonic", definition: "Grimly mocking or cynical.", type: "adjective", origin: "Greek" },
  { word: "transient", definition: "Lasting only for a short time; impermanent.", type: "adjective", origin: "Latin" },
  { word: "unilateral", definition: "Performed by or affecting only one side or party.", type: "adjective", origin: "Latin" },
  { word: "verdant", definition: "Green with grass or other rich vegetation.", type: "adjective", origin: "French" },
  { word: "ambiguous", definition: "Open to more than one interpretation; unclear.", type: "adjective", origin: "Latin" },
  { word: "belligerent", definition: "Hostile and aggressive; engaged in a war or conflict.", type: "adjective", origin: "Latin" },
  { word: "capricious", definition: "Given to sudden and unaccountable changes of mood or behavior.", type: "adjective", origin: "Italian" },
  { word: "desolate", definition: "Empty and bleak; feeling or showing misery.", type: "adjective", origin: "Latin" },
  { word: "equanimity", definition: "Mental calmness and composure, especially in a difficult situation.", type: "noun", origin: "Latin" },
  { word: "fortuitous", definition: "Happening by accident or chance rather than design.", type: "adjective", origin: "Latin" },
  { word: "garrulous", definition: "Excessively talkative, especially on trivial matters.", type: "adjective", origin: "Latin" },
  { word: "harbinger", definition: "A person or thing that announces the approach of another.", type: "noun", origin: "French" },
  { word: "idyllic", definition: "Extremely happy, peaceful, or picturesque.", type: "adjective", origin: "Greek" },
  { word: "juxtapose", definition: "To place close together for contrasting effect.", type: "verb", origin: "Latin" },
  { word: "kismet", definition: "Destiny or fate.", type: "noun", origin: "Turkish" },
  { word: "laconic", definition: "Using very few words; concise to the point of seeming rude.", type: "adjective", origin: "Greek" },
  { word: "maelstrom", definition: "A powerful whirlpool; a situation of confused movement or upheaval.", type: "noun", origin: "Dutch" },
  { word: "nascent", definition: "Just beginning to develop; emerging.", type: "adjective", origin: "Latin" },
  { word: "obsolete", definition: "No longer produced or used; out of date.", type: "adjective", origin: "Latin" },
  { word: "petrichor", definition: "The pleasant earthy smell after rain.", type: "noun", origin: "Greek" },
  { word: "quixotic", definition: "Exceedingly idealistic; unrealistic and impractical.", type: "adjective", origin: "Spanish" },
  { word: "ravenous", definition: "Extremely hungry; rapacious.", type: "adjective", origin: "French" },
  { word: "scintillate", definition: "To emit flashes of light; to sparkle or shine.", type: "verb", origin: "Latin" },
  { word: "talisman", definition: "An object thought to have magic powers and to bring good luck.", type: "noun", origin: "Arabic" },
  { word: "veracity", definition: "Conformity to facts; accuracy or habitual truthfulness.", type: "noun", origin: "Latin" },
  { word: "avarice", definition: "Extreme greed for wealth or material gain.", type: "noun", origin: "Latin" },
  { word: "bucolic", definition: "Relating to the pleasant aspects of the countryside.", type: "adjective", origin: "Greek" },
  { word: "copious", definition: "Abundant in supply or quantity.", type: "adjective", origin: "Latin" },
  { word: "debonair", definition: "Confident, stylish, and charming.", type: "adjective", origin: "French" },
  { word: "ebullient", definition: "Cheerful and full of energy.", type: "adjective", origin: "Latin" },
  { word: "felicity", definition: "Intense happiness; the ability to find appropriate expression.", type: "noun", origin: "Latin" },
  { word: "iconoclast", definition: "A person who attacks cherished beliefs or institutions.", type: "noun", origin: "Greek" },
  { word: "languid", definition: "Displaying or having a disinclination for physical exertion.", type: "adjective", origin: "Latin" },
  { word: "mercurial", definition: "Subject to sudden or unpredictable changes of mood or mind.", type: "adjective", origin: "Latin" },
  { word: "panacea", definition: "A solution or remedy for all difficulties or diseases.", type: "noun", origin: "Greek" },
  { word: "recondite", definition: "Little known; abstruse.", type: "adjective", origin: "Latin" },
  { word: "soporific", definition: "Tending to induce drowsiness or sleep.", type: "adjective", origin: "Latin" },
  { word: "taciturn", definition: "Reserved or uncommunicative in speech; saying little.", type: "adjective", origin: "Latin" },
  { word: "vicarious", definition: "Experienced in the imagination through the actions of another person.", type: "adjective", origin: "Latin" },
  { word: "acrimony", definition: "Bitterness or ill feeling.", type: "noun", origin: "Latin" },
  { word: "beguile", definition: "To charm or enchant, sometimes in a deceptive way.", type: "verb", origin: "English" },
  { word: "chicanery", definition: "The use of trickery to achieve a political or legal purpose.", type: "noun", origin: "French" },
  { word: "draconian", definition: "Excessively harsh and severe.", type: "adjective", origin: "Greek" },
  { word: "esoteric", definition: "Intended for or likely to be understood by only a small number of people.", type: "adjective", origin: "Greek" },
  { word: "flippant", definition: "Not showing a serious or respectful attitude.", type: "adjective", origin: "English" },
  { word: "hegemony", definition: "Leadership or dominance, especially by one state or group over others.", type: "noun", origin: "Greek" },
  { word: "insidious", definition: "Proceeding in a gradual, subtle way, but with harmful effects.", type: "adjective", origin: "Latin" },
  { word: "jocular", definition: "Fond of or characterized by joking; humorous.", type: "adjective", origin: "Latin" },
  { word: "loquacious", definition: "Tending to talk a great deal; talkative.", type: "adjective", origin: "Latin" },
  { word: "munificent", definition: "Larger or more generous than is usual or necessary.", type: "adjective", origin: "Latin" },
  { word: "obsequious", definition: "Obedient or attentive to an excessive degree.", type: "adjective", origin: "Latin" },
  { word: "penchant", definition: "A strong or habitual liking for something.", type: "noun", origin: "French" },
  { word: "rancor", definition: "Bitterness or resentfulness, especially when long-standing.", type: "noun", origin: "Latin" },
  { word: "spurious", definition: "Not being what it purports to be; false or fake.", type: "adjective", origin: "Latin" },
  { word: "truncate", definition: "To shorten by cutting off the top or end.", type: "verb", origin: "Latin" },
  { word: "vitriolic", definition: "Filled with bitter criticism or malice.", type: "adjective", origin: "Latin" },
  { word: "acumen", definition: "The ability to make good judgments and quick decisions.", type: "noun", origin: "Latin" },
  { word: "buffoon", definition: "A ridiculous but amusing person; a clown.", type: "noun", origin: "Italian" },
  { word: "cogent", definition: "Clear, logical, and convincing.", type: "adjective", origin: "Latin" },
  { word: "didactic", definition: "Intended to teach, particularly in having moral instruction.", type: "adjective", origin: "Greek" },
  { word: "elucidate", definition: "To make something clear; to explain.", type: "verb", origin: "Latin" },
  { word: "frivolous", definition: "Not having any serious purpose or value.", type: "adjective", origin: "Latin" },
  { word: "hubris", definition: "Excessive pride or self-confidence.", type: "noun", origin: "Greek" },
  { word: "intrepid", definition: "Fearless; adventurous.", type: "adjective", origin: "Latin" },
  { word: "kinetic", definition: "Relating to or resulting from motion.", type: "adjective", origin: "Greek" },
  { word: "lurid", definition: "Very vivid in color; gruesome or sensational.", type: "adjective", origin: "Latin" },
  { word: "nonchalant", definition: "Feeling or appearing casually calm and relaxed.", type: "adjective", origin: "French" },
  { word: "ostentatious", definition: "Characterized by vulgar or pretentious display.", type: "adjective", origin: "Latin" },
  { word: "perfunctory", definition: "Carried out with minimal effort or reflection.", type: "adjective", origin: "Latin" },
  { word: "repudiate", definition: "To refuse to accept or be associated with.", type: "verb", origin: "Latin" },
  { word: "sanguine", definition: "Optimistic or positive, especially in a difficult situation.", type: "adjective", origin: "Latin" },
  { word: "tempestuous", definition: "Characterized by strong and turbulent or conflicting emotion.", type: "adjective", origin: "Latin" },
  { word: "utilitarian", definition: "Designed to be useful or practical rather than attractive.", type: "adjective", origin: "Latin" },
  { word: "vindicate", definition: "To clear someone of blame or suspicion.", type: "verb", origin: "Latin" },
  { word: "wistful", definition: "Having or showing a feeling of vague or regretful longing.", type: "adjective", origin: "English" },
  { word: "auspicious", definition: "Conducive to success; favorable.", type: "adjective", origin: "Latin" },
  { word: "candor", definition: "The quality of being open and honest in expression.", type: "noun", origin: "Latin" },
  { word: "disparage", definition: "To regard or represent as being of little worth.", type: "verb", origin: "French" },
  { word: "eclectic", definition: "Deriving ideas or style from a broad and diverse range of sources.", type: "adjective", origin: "Greek" },
  { word: "facetious", definition: "Treating serious issues with deliberately inappropriate humor.", type: "adjective", origin: "French" },
  { word: "grandiloquent", definition: "Pompous or extravagant in language or style.", type: "adjective", origin: "Latin" },
  { word: "inquisitive", definition: "Curious or inquiring; eager to learn.", type: "adjective", origin: "Latin" },
  { word: "juggernaut", definition: "A huge, powerful, and overwhelming force or institution.", type: "noun", origin: "Sanskrit" },
  { word: "lucid", definition: "Expressed clearly; easy to understand.", type: "adjective", origin: "Latin" },
  { word: "morose", definition: "Sullen and ill-tempered.", type: "adjective", origin: "Latin" },
  { word: "noxious", definition: "Harmful, poisonous, or very unpleasant.", type: "adjective", origin: "Latin" },
  { word: "perpetuate", definition: "To make something continue indefinitely.", type: "verb", origin: "Latin" },
  { word: "reticent", definition: "Not revealing one's thoughts or feelings readily.", type: "adjective", origin: "Latin" },
  { word: "accolade", definition: "An award or privilege granted as a special honor.", type: "noun", origin: "French" },
  { word: "brazen", definition: "Bold and without shame.", type: "adjective", origin: "English" },
  { word: "cumbersome", definition: "Large or heavy and therefore difficult to carry or use.", type: "adjective", origin: "English" },
  { word: "dystopia", definition: "An imagined state or society in which there is great suffering.", type: "noun", origin: "Greek" },
  { word: "fallacy", definition: "A mistaken belief based on unsound argument.", type: "noun", origin: "Latin" },
  { word: "grandiose", definition: "Impressive and imposing in appearance or style.", type: "adjective", origin: "Italian" },
  { word: "hyperbole", definition: "Exaggerated statements not meant to be taken literally.", type: "noun", origin: "Greek" },
  { word: "indomitable", definition: "Impossible to subdue or defeat.", type: "adjective", origin: "Latin" },
  { word: "kafkaesque", definition: "Marked by surreal distortion and a sense of impending danger.", type: "adjective", origin: "Czech" },
  { word: "magnate", definition: "A wealthy and influential person, especially in business.", type: "noun", origin: "Latin" },
  { word: "nuance", definition: "A subtle difference in meaning, expression, or sound.", type: "noun", origin: "French" },
  { word: "oxymoron", definition: "A figure of speech in which contradictory terms appear together.", type: "noun", origin: "Greek" },
  { word: "precarious", definition: "Not securely held or in position; dangerously likely to fall.", type: "adjective", origin: "Latin" },
  { word: "rhetoric", definition: "The art of effective or persuasive speaking or writing.", type: "noun", origin: "Greek" },
  { word: "stoic", definition: "Enduring pain and hardship without showing feelings or complaining.", type: "adjective", origin: "Greek" },
  { word: "testament", definition: "A thing that serves as a sign or evidence of a fact or quality.", type: "noun", origin: "Latin" },
  { word: "utopia", definition: "An imagined place or state where everything is perfect.", type: "noun", origin: "Greek" },
  { word: "vagrant", definition: "A person without a settled home or regular work.", type: "noun", origin: "French" },
  { word: "zealous", definition: "Having or showing great energy or enthusiasm for a cause.", type: "adjective", origin: "Greek" },
  { word: "aplomb", definition: "Self-confidence or assurance, especially in a demanding situation.", type: "noun", origin: "French" },
  { word: "capitulate", definition: "To cease to resist an opponent or an unwelcome demand.", type: "verb", origin: "Latin" },
  { word: "deleterious", definition: "Causing harm or damage.", type: "adjective", origin: "Greek" },
  { word: "embargo", definition: "An official ban on trade or other commercial activity.", type: "noun", origin: "Spanish" },
  { word: "fiasco", definition: "A thing that is a complete failure, especially in a ludicrous way.", type: "noun", origin: "Italian" },
  { word: "gambit", definition: "An act or remark intended to gain an advantage.", type: "noun", origin: "Italian" },
  { word: "hackneyed", definition: "Lacking significance through overuse; unoriginal.", type: "adjective", origin: "English" },
  { word: "impeccable", definition: "In accordance with the highest standards; faultless.", type: "adjective", origin: "Latin" },
  { word: "jingoism", definition: "Extreme patriotism, especially in the form of aggressive foreign policy.", type: "noun", origin: "English" },
  { word: "keepsake", definition: "A small item kept in memory of the person who gave it.", type: "noun", origin: "English" },
  { word: "maverick", definition: "An unorthodox or independent-minded person.", type: "noun", origin: "English" },
  { word: "nemesis", definition: "An opponent or rival whom one cannot overcome; one's downfall.", type: "noun", origin: "Greek" },
  { word: "opaque", definition: "Not able to be seen through; not transparent.", type: "adjective", origin: "Latin" },
  { word: "pinnacle", definition: "The most successful point; the culmination.", type: "noun", origin: "Latin" },
  { word: "quandary", definition: "A state of perplexity or uncertainty over what to do.", type: "noun", origin: "English" },
  { word: "recluse", definition: "A person who lives a solitary life and tends to avoid others.", type: "noun", origin: "Latin" },
  { word: "scrutinize", definition: "To examine or inspect closely and thoroughly.", type: "verb", origin: "Latin" },
  { word: "tumultuous", definition: "Making a loud, confused noise; excited or angry.", type: "adjective", origin: "Latin" },
  { word: "usurp", definition: "To take a position of power illegally or by force.", type: "verb", origin: "Latin" },
  { word: "venerate", definition: "To regard with great respect or reverence.", type: "verb", origin: "Latin" },
  { word: "wrangle", definition: "A dispute or argument, typically one that is long and complicated.", type: "noun", origin: "English" },
  { word: "xenophile", definition: "A person who is attracted to foreign cultures and people.", type: "noun", origin: "Greek" },
  { word: "yeoman", definition: "A man holding a small landed estate; a freeholder.", type: "noun", origin: "English" },
  { word: "cipher", definition: "A secret way of writing; a code; a zero.", type: "noun", origin: "Arabic" },
  { word: "tsunami", definition: "A long high sea wave caused by an earthquake or volcanic eruption.", type: "noun", origin: "Japanese" },
  { word: "schadenfreude", definition: "Pleasure derived from another person's misfortune.", type: "noun", origin: "German" },
  { word: "avatar", definition: "An icon or figure representing a particular person; an incarnation.", type: "noun", origin: "Sanskrit" },
  { word: "bravado", definition: "A bold manner or show of boldness intended to impress.", type: "noun", origin: "Spanish" },
  { word: "carousel", definition: "A rotating machine or conveyor; a merry-go-round.", type: "noun", origin: "French" },
  { word: "dilemma", definition: "A situation in which a difficult choice has to be made.", type: "noun", origin: "Greek" },
  { word: "filigree", definition: "Ornamental work of fine wire; intricate design.", type: "noun", origin: "Italian" },
  { word: "guru", definition: "An influential teacher or authority in a particular field.", type: "noun", origin: "Sanskrit" },
  { word: "incognito", definition: "Having one's true identity concealed.", type: "adjective", origin: "Italian" },
  { word: "mitigate", definition: "To make less severe, serious, or painful.", type: "verb", origin: "Latin" },
  { word: "oblique", definition: "Neither parallel nor at a right angle; not straightforward.", type: "adjective", origin: "Latin" },
  { word: "plethora", definition: "A large or excessive amount of something.", type: "noun", origin: "Greek" },
  { word: "rebuke", definition: "To express sharp disapproval or criticism.", type: "verb", origin: "French" },
  { word: "solace", definition: "Comfort or consolation in a time of distress or sadness.", type: "noun", origin: "Latin" },
  { word: "tundra", definition: "A vast, flat, treeless Arctic region with permanently frozen subsoil.", type: "noun", origin: "Russian" },
  { word: "vendetta", definition: "A prolonged bitter quarrel with or campaign against someone.", type: "noun", origin: "Italian" },
  { word: "amnesty", definition: "An official pardon for people convicted of offenses.", type: "noun", origin: "Greek" },
  { word: "bohemian", definition: "A person with artistic or literary interests who disregards conventions.", type: "noun", origin: "French" },
  { word: "crescendo", definition: "A gradual increase in loudness or intensity.", type: "noun", origin: "Italian" },
  { word: "doppelganger", definition: "An apparition or double of a living person.", type: "noun", origin: "German" },
  { word: "flamboyant", definition: "Tending to attract attention because of confidence and stylishness.", type: "adjective", origin: "French" },
  { word: "haphazard", definition: "Lacking any obvious principle of organization; random.", type: "adjective", origin: "English" },
  { word: "impromptu", definition: "Done without being planned or rehearsed.", type: "adjective", origin: "French" },
  { word: "juxtaposition", definition: "The fact of two things being placed close together for contrast.", type: "noun", origin: "Latin" },
  { word: "labyrinthine", definition: "Irregular and twisting like a labyrinth; intricate and confusing.", type: "adjective", origin: "Greek" },
  { word: "meander", definition: "To follow a winding course; to wander aimlessly.", type: "verb", origin: "Greek" },
  { word: "nirvana", definition: "A transcendent state free from suffering and individual existence.", type: "noun", origin: "Sanskrit" },
  { word: "osmosis", definition: "A gradual, often unconscious process of assimilation.", type: "noun", origin: "Greek" },
  { word: "paragon", definition: "A model of excellence or perfection.", type: "noun", origin: "Italian" },
  { word: "renaissance", definition: "A revival of or renewed interest in something.", type: "noun", origin: "French" },
  { word: "silhouette", definition: "The dark shape or outline of someone or something visible against a lighter background.", type: "noun", origin: "French" },
  { word: "taboo", definition: "A social or religious custom prohibiting a particular practice.", type: "noun", origin: "Tongan" },
  { word: "veranda", definition: "A roofed platform along the outside of a house.", type: "noun", origin: "Hindi" },
  { word: "wanderlust", definition: "A strong desire to travel and explore the world.", type: "noun", origin: "German" },
  { word: "archipelago", definition: "A group of islands.", type: "noun", origin: "Italian" },
  { word: "bliss", definition: "Perfect happiness; great joy.", type: "noun", origin: "English" },
  { word: "connoisseur", definition: "An expert judge in matters of fine art or taste.", type: "noun", origin: "French" },
  { word: "enigmatic", definition: "Difficult to interpret or understand; mysterious.", type: "adjective", origin: "Greek" },
  { word: "fathom", definition: "To understand after much thought.", type: "verb", origin: "English" },
  { word: "gallant", definition: "Brave; heroic; chivalrous.", type: "adjective", origin: "French" },
  { word: "impervious", definition: "Not allowing fluid to pass through; unable to be affected.", type: "adjective", origin: "Latin" },
  { word: "jurisdiction", definition: "The official power to make legal decisions and judgments.", type: "noun", origin: "Latin" },
  { word: "kindle", definition: "To light or set on fire; to arouse or inspire.", type: "verb", origin: "Norse" },
  { word: "lament", definition: "A passionate expression of grief or sorrow.", type: "noun", origin: "Latin" },
  { word: "malevolent", definition: "Having or showing a wish to do evil to others.", type: "adjective", origin: "Latin" },
  { word: "nomadic", definition: "Living the life of one who moves from place to place.", type: "adjective", origin: "Greek" },
  { word: "poignant", definition: "Evoking a keen sense of sadness or regret.", type: "adjective", origin: "French" },
  { word: "relentless", definition: "Oppressively constant; showing no abatement of intensity.", type: "adjective", origin: "English" },
  { word: "sublime", definition: "Of such excellence or beauty as to inspire great admiration.", type: "adjective", origin: "Latin" },
  { word: "turbulent", definition: "Characterized by conflict, disorder, or confusion.", type: "adjective", origin: "Latin" },
  { word: "vivid", definition: "Producing powerful feelings or strong, clear images in the mind.", type: "adjective", origin: "Latin" },
  { word: "chronicle", definition: "A factual written account of important events in order of time.", type: "noun", origin: "Greek" },
  { word: "anthology", definition: "A published collection of poems or other pieces of writing.", type: "noun", origin: "Greek" },
  { word: "bizarre", definition: "Very strange or unusual.", type: "adjective", origin: "French" },
  { word: "candid", definition: "Truthful and straightforward; frank.", type: "adjective", origin: "Latin" },
  { word: "demeanor", definition: "Outward behavior or bearing.", type: "noun", origin: "French" },
  { word: "elaborate", definition: "Involving many carefully arranged parts; detailed.", type: "adjective", origin: "Latin" },
  { word: "futile", definition: "Incapable of producing any useful result; pointless.", type: "adjective", origin: "Latin" },
  { word: "gallantry", definition: "Courageous behavior, especially in battle; polite attention given to women.", type: "noun", origin: "French" },
  { word: "heresy", definition: "Belief or opinion contrary to orthodox religious doctrine.", type: "noun", origin: "Greek" },
  { word: "indigenous", definition: "Originating or occurring naturally in a particular place.", type: "adjective", origin: "Latin" },
  { word: "jovial", definition: "Cheerful and friendly.", type: "adjective", origin: "Latin" },
  { word: "kudos", definition: "Praise and honor received for an achievement.", type: "noun", origin: "Greek" },
  { word: "lullaby", definition: "A quiet, gentle song sung to send a child to sleep.", type: "noun", origin: "English" },
  { word: "manifest", definition: "Clear or obvious to the eye or mind.", type: "adjective", origin: "Latin" },
  { word: "nonchalance", definition: "The state of being calm and relaxed about everything.", type: "noun", origin: "French" },
  { word: "odyssey", definition: "A long and eventful or adventurous journey.", type: "noun", origin: "Greek" },
  { word: "paladin", definition: "A leading champion of a cause; a heroic defender.", type: "noun", origin: "French" },
  { word: "repartee", definition: "Conversation or speech characterized by quick, witty comments.", type: "noun", origin: "French" },
  { word: "synchronize", definition: "To cause to operate or occur at the same time or rate.", type: "verb", origin: "Greek" },
  { word: "tenacity", definition: "The quality of holding firmly to something; persistence.", type: "noun", origin: "Latin" },
  { word: "unwieldy", definition: "Difficult to carry or move because of size, shape, or weight.", type: "adjective", origin: "English" },
  { word: "visceral", definition: "Relating to deep inward feelings rather than to the intellect.", type: "adjective", origin: "Latin" },
  { word: "whimsy", definition: "Playfully quaint or fanciful behavior or humor.", type: "noun", origin: "English" },
  { word: "astute", definition: "Having an ability to accurately assess situations and turn them to advantage.", type: "adjective", origin: "Latin" },
  { word: "bombastic", definition: "High-sounding but with little meaning; inflated.", type: "adjective", origin: "French" },
  { word: "cosmopolitan", definition: "Familiar with and at ease in many different cultures.", type: "adjective", origin: "Greek" },
  { word: "dogma", definition: "A principle or set of principles laid down by an authority as true.", type: "noun", origin: "Greek" },
  { word: "ecstasy", definition: "An overwhelming feeling of great happiness or joyful excitement.", type: "noun", origin: "Greek" },
  { word: "formidable", definition: "Inspiring fear or respect through being impressively powerful.", type: "adjective", origin: "Latin" },
  { word: "gargantuan", definition: "Enormous; of great size.", type: "adjective", origin: "French" },
  { word: "hedonism", definition: "The pursuit of pleasure as the highest good.", type: "noun", origin: "Greek" },
  { word: "impeccable", definition: "In accordance with the highest standards of propriety; faultless.", type: "adjective", origin: "Latin" },
  { word: "jagged", definition: "Having rough, sharp points protruding.", type: "adjective", origin: "English" },
  { word: "killjoy", definition: "A person who deliberately spoils the enjoyment of others.", type: "noun", origin: "English" },
  { word: "luminescent", definition: "Emitting light not caused by heat.", type: "adjective", origin: "Latin" },
  { word: "misnomer", definition: "A wrong or inaccurate name or designation.", type: "noun", origin: "French" },
  { word: "nefarious", definition: "Wicked or criminal.", type: "adjective", origin: "Latin" },
  { word: "opulence", definition: "Great wealth or luxuriousness.", type: "noun", origin: "Latin" },
  { word: "panache", definition: "Flamboyant confidence of style or manner.", type: "noun", origin: "French" },
  { word: "requiem", definition: "A mass for the repose of the souls of the dead; a musical tribute.", type: "noun", origin: "Latin" },
  { word: "somber", definition: "Dark or dull in color or tone; gloomy.", type: "adjective", origin: "French" },
  { word: "travesty", definition: "A false, absurd, or distorted representation of something.", type: "noun", origin: "French" },
  { word: "zenith", definition: "The time at which something is most powerful or successful.", type: "noun", origin: "Arabic" }
];
